name: CI - Push to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  issues: write
  repository-projects: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
    format:
      name: Format Code
      runs-on: ubuntu-latest
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      steps:
        - name: Check out code using Git
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            ref: ${{ github.head_ref }}
            token: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Install Tools & Dependencies
          uses: withstudiocms/automations/.github/actions/install@main
  
        - name: Format code
          run: pnpm run lint:fix
  
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
          with:
            commit_message: '[ci] lint'
            branch: ${{ github.head_ref }}

    changeset-release:
      name: Changeset Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

        - name: Install Tools & Dependencies
          uses: withstudiocms/automations/.github/actions/install@main

        - name: Build Packages
          run: pnpm ci:build

        - name: Create Release Pull Request or Publish to npm
          id: changesets
          uses: changesets/action@v1
          with:
              setupGitUser: true
              commit: "👷 [ci]: Version Packages"
              title: "👷 [ci]: Ready for Release"
              version: pnpm ci:version
              publish: pnpm ci:publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: Add Label to CI PR
          if: ${{ steps.changesets.outputs.hasChangesets == 'true' }}
          run: gh pr edit "$PR_URL" --add-label "ci"
          env:
            PR_URL: ${{ steps.changesets.outputs.pull_request_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}